library(drake)
library(here)

source(here("R/packages.R"))
source(here("R/functions.R"))

plan <- drake_plan(
  gss_1996 = readRDS(here("data/gss_1996.RDS")),
  cross_walk = read_csv(here("data/new_crosswalk.csv"), col_types = cols()),
  block_info = read_csv(here("data/block_info_bayesact.csv"), col_types = cols()),
  cross_block = left_join(cross_walk, block_info, by = "term") %>% 
                select(term, isco88, blocks_4),
  gss_block = join_data(cw = cross_walk, bi = block_info, gss = gss_1996),
  cont_vars = c("year", "id", "ballot", "age", "relig", "realinc", 
                "pasei10", "childs", "educ", "prestg80"),
  emotion_vars = c("angry", "calm", "anxious", "hapfeel", "outraged", "sad", "ashamed", "excited",
                    "lonely", "fearful", "ovrjoyed", "worried", "contentd", "anxious", "restless",
                    "madat", "proud"),
  cat_vars = c("race", "sex", "spwrksta", "blocks_4", "income", "class", 
               "wrkstat", "region", "health", "degree", "term"),
  gss_recoded = recode_data(d = gss_block, emotion_vars = emotion_vars, 
                            cont_vars = cont_vars, cat_vars = cat_vars),
  occs_in_an = read_csv(here("data/occs_in_analysis.csv")),
  modifiers = read_csv(here("data/FullSurveyorInteract_Modifiers.csv")),
  occs_emotions = calc_char_emotions(occs = occs_in_an, mods = modifiers),
  dist_hist = make_hist_plot(occs_emotions),
  gss_long_emotions = join_gss_and_emotions(gss_emotions = gss_recoded, 
                                            occs_emotions = occs_emotions),
  analysis_vars = c("count", "sex", "age_cat", "race", "degree", "income", 
                    "prestg80", "children"),
  gss_analysis = remove_missing_cases(gss_long_emotions = gss_long_emotions,
                                      vars = analysis_vars),
  descriptive_table = write_descriptive_table(gss_analysis, "descriptives_table"),
  emo_table = make_emotion_table(gss_analysis, occs_emotions, "emo_table.html"),
  dv_vis = make_dist_vis(gss_analysis, "dv_vis"),
  #nb_bin = run_binary_models(family = "negbinom",
                     #d = gss_analysis),
  logit_bin = run_binary_models(family = "logit",
                                d = gss_analysis),
  #nb_control = run_control_models(family = "negbinom",
                                  #d = gss_analysis),
  logit_control = run_control_models(family = "logit",
                                     d = gss_analysis),
  logit_int_models = run_int_models(d = gss_analysis),
  #good_power_mod = run_emotion_specific_int(d = gss_analysis, 
                                      # emo_type = "good_powerful"),
  #bad_weak_mod = run_emotion_specific_int(d = gss_analysis, 
                                         # emo_type = "bad_weak"),
  #bad_power_mod = run_emotion_specific_int(d = gss_analysis, 
                                          # emo_type = "bad_powerful"),
  main_results = write_model_results(m = list(logit_bin, logit_control),
                                   type = "base",
                                   fn = "main_table"),
  int_results = write_model_results(m = logit_int_models,
                                    type = "int",
                                    fn = "int_table"),
  # gp_results = write_model_results(m = good_power_mod,
  #                                  type = "emotion",
  #                                  fn = "good_power_table"),
  # bw_results = write_model_results(m = bad_weak_mod,
  #                                  type = "emotion",
  #                                  fn = "bad_weak_table"),
  # bp_results = write_model_results(m = bad_power_mod,
  #                                  type = "emotion",
  #                                  fn = "bad_power_table"),
  emo_plot = make_emotion_plot(m = logit_control, fn = "emo_int_plot"),
  main_oced_plot = make_main_oced_plot(logit_control, fn = "main_eff_plot"),
  cor_test = calc_corr_test(d = occs_emotions, mod = logit_control,
                            m_number = 3),
  income_int_plot = make_int_plots(mod = logit_int_models, 
                                   m_number = 1,
                                   var = "income_std",
                                   subt = "by income level",
                                   legend_label = "income (std)",
                                   fn = "income_int_plot"),
  education_int_plot = make_int_plots(mod = logit_int_models,
                                      var = "degree",
                                      m_number = 2,
                                      subt = "by highest degree earned",
                                      legend_label = "degree",
                                      fn = "degree_int_plot"),
  sex_int_plot = make_int_plots(mod = logit_int_models,
                                var = "sex",
                                m_number = 4,
                                subt = "by sex",
                                legend_label = "sex",
                                fn = "sex_int_plot"),
  #cum_logit_models = run_cumulative_logit_models(gss_analysis),
  #frac_logit_models = run_fractional_logit_models(gss_analysis)
  #model_comparison = make_model_comparison_plot(cum_logit_models, 
                                               #frac_logit_models,
                                               #nb_bin,
                                               #nb_control)
  
 )

make(plan, lock_envir = FALSE)
